export const atlas = {
    nodes: [
        {id: "Pumpkin Fields", group: 1, isAnchor: true, fx: -90, fy: 115},
        {id: "Paper Trove", group: 1},
        {id: "Atrium", group: 1},
        {id: "Workshop", group: 1},
        {id: "Reflective Island", group: 1},
        {id: "Forgotten Mounds", group: 1},
        {id: "Manor", group: 1},
        {id: "Flooded Passage", group: 1},
        {id: "Mangroves", group: 1},
        {id: "Rocky Pass", group: 1},
        {id: "Sink Whole", group: 1},
        {id: "Circus", group: 1},
        {id: "Forgotten Dias", group: 1},
        {id: "Engine Room", group: 1},
        {id: "The Kings Chamber", group: 1},
        {id: "Rainbow Pond", group: 1},
        {id: "Imperial Bridge", group: 1},
        {id: "Collage Halls", group: 1},
        {id: "Megalithic Throne", group: 1},

        {id: "Meadows", group: 2, isAnchor: true, fx: -90, fy: -120},
{       id: "Great Stage", group: 2},
        {id: "Lumber Yard", group: 2},
        {id: "Murky Trench", group: 2},
        {id: "Broken Crypt", group: 2},
        {id: "Twined Monoliths", group: 2}, 
        {id: "Monastery", group: 2},
        {id: "Padded Hallways", group: 2},
        {id: "Glyphic Landscape", group: 2},
        {id: "Eroded City", group: 2},
        {id: "Copper Vessel", group: 2},
        {id: "Cistern", group: 2},
        {id: "Deserted Campsite", group: 2},
        {id: "Silken Prairie", group: 2},
        {id: "Sterile Clinic", group: 2},
        {id: "Stone Huts", group: 2},
        {id: "Tarred River", group: 2},
        {id: "Mycilic Jungle", group: 2},
        {id: "Vaal Asylum", group: 2},

        
        {id: "Trade District", group: 3, isAnchor: true, fx: 85, fy: -135},
        {id: "Bloody Altar", group: 3},
        {id: "Rapids", group: 3},
        {id: "Crossroads", group: 3},
        {id: "Giant Steps", group: 3},
        {id: "Resonating Henge", group: 3},
        {id: "Polar Dunes", group: 3},
        {id: "Molten Kiln", group: 3},
        {id: "Planetarium", group: 3},
        {id: "Skeletal Oasis", group: 3},
        {id: "Cavernous Skull", group: 3},
        {id: "Blockade", group: 3},
        {id: "Decaying Moon", group: 3},
        {id: "Maddening Hollow", group: 3},
        {id: "Primeval Tomb", group: 3},
        {id: "Lagoon", group: 3},
        {id: "Crumbled Tower", group: 3},
        {id: "Assembly", group: 3},
        {id: "Shark Shoals", group: 3},
        {id: "Battlefield", group: 3},

        {id: "Grand Opera Hall", group: 4, isAnchor: true, fx: 100, fy: 120},
        {id: "Clearing", group: 4},
        {id: "Junk Pile", group: 4},
        {id: "Giant Garden", group: 4},
        {id: "Apiary", group: 4},
        {id: "Metal Labyrinth", group: 4},
        {id: "Bilge", group: 4},
        {id: "Echoing Sound", group: 4},
        {id: "Undisturbed Tomb", group: 4},
        {id: "Salt Flats", group: 4},
        {id: "Sealed Door", group: 4},
        {id: "Gilded Bathhouse", group: 4},
        {id: "Gaseous Swamp", group: 4},
        {id: "Mercury Pools", group: 4},
        {id: "Quite Forum", group: 4},
        {id: "Village Outskirts", group: 4},
        {id: "Sandbar", group: 4},
        {id: "Shaded Ruins", group: 4},
        {id: "Precursor's Study", group: 4},
        {id: "Windmill", group: 4},
        {id: "Dreamlands", group: 4},
        {id: "Display Room", group: 4},
    ],
    links: [
        //////////////

        {source: "Pumpkin Fields", target: "Paper Trove"},

        {source: "Paper Trove", target: "Workshop"},
        {source: "Paper Trove", target: "Atrium"},
        {source: "Workshop", target: "Reflective Island"},
        {source: "Reflective Island", target: "Forgotten Mounds"},
        {source: "Atrium", target: "Windmill"},
        {source: "Reflective Island", target: "Windmill"},
        {source: "Windmill", target: "Flooded Passage"},
        {source: "Forgotten Mounds", target: "Flooded Passage"},
        {source: "Atrium", target: "Rocky Pass"},
        {source: "Rocky Pass", target: "Mangroves"},
        {source: "Mangroves", target: "Manor"},
        {source: "Flooded Passage", target: "Manor"},
        {source: "Manor", target: "Sink Whole"},
        {source: "Mangroves", target: "Sink Whole"},
        {source: "Rocky Pass", target: "Circus"},
        {source: "Circus", target: "Forgotten Dias"},
        {source: "Mangroves", target: "Forgotten Dias"},
        {source: "Forgotten Dias", target: "Rainbow Pond"},
        {source: "Sink Whole", target: "Rainbow Pond"},
        {source: "Circus", target: "Collage Halls"},
        {source: "Forgotten Dias", target: "Engine Room"},
        {source: "Engine Room", target: "The Kings Chamber"},
        {source: "Rainbow Pond", target: "The Kings Chamber"},
        {source: "Collage Halls", target: "Imperial Bridge"},
        {source: "Imperial Bridge", target: "Megalithic Throne"},
        {source: "Rainbow Pond", target: "Megalithic Throne"},
        //////////////
        {source: "Meadows", target: "Great Stage"},
        {source: "Great Stage", target: "Lumber Yard"},
        {source: "Lumber Yard", target: "Murky Trench"},
        {source: "Murky Trench", target: "Broken Crypt"},
        {source: "Broken Crypt", target: "Twined Monoliths"},
        {source: "Twined Monoliths", target: "Flooded Passage"},
        {source: "Twined Monoliths", target: "Glyphic Landscape"},
        {source: "Glyphic Landscape", target: "Eroded City"},
        {source: "Eroded City", target: "Sink Whole"},
        {source: "Lumber Yard", target: "Monastery"},
        {source: "Monastery", target: "Padded Hallways"},
        {source: "Murky Trench", target: "Padded Hallways"},
        {source: "Padded Hallways", target: "Mercury Pools"},
        {source: "Mercury Pools", target: "Copper Vessel"},
        {source: "Copper Vessel", target: "Eroded City"},
        {source: "Great Stage", target: "Sterile Clinic"},
        {source: "Sterile Clinic", target: "Giant Garden"},
        {source: "Giant Garden", target: "Silken Prairie"},
        {source: "Silken Prairie", target: "Deserted Campsite"},
        {source: "Lumber Yard", target: "Deserted Campsite"},
        {source: "Deserted Campsite", target: "Cistern"},
        {source: "Cistern", target: "Mercury Pools"},
        {source: "Silken Prairie", target: "Mycilic Jungle"},
        {source: "Mycilic Jungle", target: "Tarred River"},
        {source: "Tarred River", target: "Stone Huts"},
        {source: "Cistern", target: "Stone Huts"},
        {source: "Mercury Pools", target: "Stone Huts"}, 
        {source: "Mycilic Jungle", target: "Vaal Asylum"},

        //////////////
        {source: "Trade District", target: "Bloody Altar"},
        {source: "Bloody Altar", target: "Rapids"},
        {source: "Rapids", target: "Crossroads"},
        {source: "Crossroads", target: "Giant Steps"},
        {source: "Giant Steps", target: "Resonating Henge"},
        {source: "Resonating Henge", target: "Gilded Bathhouse"},
        {source: "Rapids", target: "Skeletal Oasis"},
        {source: "Skeletal Oasis", target: "Planetarium"},
        {source: "Planetarium", target: "Village Outskirts"},
        {source: "Crossroads", target: "Molten Kiln"},
        {source: "Planetarium", target: "Molten Kiln"},
        {source: "Molten Kiln", target: "Polar Dunes"},
        {source: "Crossroads", target: "Polar Dunes"},
        {source: "Resonating Henge", target: "Polar Dunes"},
        {source: "Skeletal Oasis", target: "Cavernous Skull"},
        {source: "Cavernous Skull", target: "Blockade"},
        {source: "Planetarium", target: "Blockade"},
        {source: "Rapids", target: "Decaying Moon"},
        {source: "Decaying Moon", target: "Maddening Hollow"},
        {source: "Trade District", target: "Maddening Hollow"},
        {source: "Maddening Hollow", target: "Primeval Tomb"},
        {source: "Primeval Tomb", target: "Crumbled Tower"},
        {source: "Decaying Moon", target: "Crumbled Tower"},
        {source: "Blockade", target: "Crumbled Tower"},
        {source: "Crumbled Tower", target: "Assembly"},
        {source: "Crumbled Tower", target: "Shark Shoals"},
        {source: "Primeval Tomb", target: "Lagoon"},
        {source: "Lagoon", target: "Shark Shoals"},
        {source: "Shark Shoals", target: "Battlefield"},
        {source: "Assembly", target: "Stone Huts"},
        {source: "Battlefield", target: "Vaal Asylum"},


        //////////////
        {source: "Grand Opera Hall", target: "Display Room"},
        {source: "Display Room", target: "Junk Pile"},
        {source: "Junk Pile", target: "Imperial Bridge"},
        {source: "Junk Pile", target: "Metal Labyrinth"},
        {source: "Metal Labyrinth", target: "Salt Flats"},
        {source: "Salt Flats", target: "Megalithic Throne"},
        {source: "Display Room", target: "Precursor's Study"},
        {source: "Precursor's Study", target: "Apiary"},
        {source: "Apiary", target: "Junk Pile"},
        {source: "Junk Pile", target: "Echoing Sound"},
        {source: "Echoing Sound", target: "Gaseous Swamp"},
        {source: "Salt Flats", target: "Gaseous Swamp"},
        {source: "Display Room", target: "Sandbar"},
        {source: "Grand Opera Hall", target: "Sealed Door"},
        {source: "Sealed Door", target: "Dreamlands"},
        {source: "Dreamlands", target: "Quite Forum"},
        {source: "Sandbar", target: "Quite Forum"},
        {source: "Dreamlands", target: "Undisturbed Tomb"},
        {source: "Undisturbed Tomb", target: "Quite Forum"},
        {source: "Grand Opera Hall", target: "Clearing"},
        {source: "Clearing", target: "Undisturbed Tomb"},
        {source: "Gaseous Swamp", target: "Shaded Ruins"},
        {source: "Clearing", target: "Gilded Bathhouse"},
        {source: "Gilded Bathhouse", target: "Bilge"},
        {source: "Bilge", target: "Village Outskirts"},
        {source: "Village Outskirts", target: "Shaded Ruins"}
    ]
};